spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/demo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
server:
  port: 8080
logging:
  file:
    name: ./log/my.log